
networks:
  backend-net:
    driver: bridge
  database-net:
    driver: bridge

services:

  postgres:
    image: postgres:17.10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database-net
      
  nginx:
    image: nginx
    ports:
      - "8085:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend-net
    depends_on:
      - statusservice1
      - statusservice2
      - statusservice3


  logservice:
    build: ./log-service
    networks: 
      - backend-net
      - database-net
  
  statusservice1:
    build: ./status-service
    networks:
      - backend-net
  
  statusservice2:
    build: ./status-service
    networks:
      - backend-net
  
  statusservice3:
    build: ./status-service
    networks:
      - backend-net

  systeminfoservice:
    build: ./system-info-service
    networks:
      - backend-net

volumes:
  postgres_data: