events {
    worker_connections 1024;
}

http {
    upstream backend {
        server statusservice1:3001 weight=3;
        server statusservice2:3001;
        server statusservice3:3001;
    }

    server {
        listen 80;

        server_name status.127.0.0.1.nip.io;

        location / {
            proxy_pass http://backend;
        }
        
    }

    server {
        listen 80;

        server_name system.127.0.0.1.nip.io;

        location / {
            proxy_pass http://systeminfoservice:3002;
        }
    }

    server {
        listen 80;

        server_name log.127.0.0.1.nip.io;

        location / {
            proxy_pass http://logservice:3003;
        }
    }
}