events {
    worker_connections 1024;
}

http {

    server {
        listen 80;

        server_name status.127.0.0.1.nip.io;

        location /status {
            proxy_pass http://statusservice:3001;
        }
    }

    server {
        listen 80;

        server_name system.127.0.0.1.nip.io;

        location /system {
            proxy_pass http://systeminfoservice:3002;
        }
    }

    server {
        listen 80;

        server_name log.127.0.0.1.nip.io;

        location /logs {
            proxy_pass http://logservice:3003;
        }
    }
}